# Generated by Django 3.2.5 on 2021-11-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AddField(
            model_name='manga',
            name='cover',
            field=models.ImageField(default=True, upload_to='C:/mangasofpicture'),
        ),
    ]
