# Generated by Django 3.2.5 on 2021-11-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211104_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, default=True, upload_to='templates/photo')),
                ('price1', models.IntegerField(verbose_name='Цена')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
